services:
  - type: web
    name: png-school-enrollment-verification
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
